name: Gravityblast
description: by Andrea Franz
meta_description: "dev blog by Andrea Franz"
title: "Gravityblast - dev blog by Andrea Franz"
cover: /assets/images/covers/urban-astronaut-1500.jpg

permalink: pretty
markdown: kramdown
highlighter: rouge
paginate: 5
domain_name: 'http://gravityblast.com'
google_analytics: 'UA-129369-13'
gems:
  - jekyll-paginate
  - jekyll-sitemap

author:         'Andrea Franz'
author_email:   'andrea@gravityblast.com'

url:             'http://gravityblast.com'
rss_title:       'Andrea Franz'
rss_description: 'dev blog by Andrea Franz'

